// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaOIOHdDBhftD66uSiz41qmxC2aRMHepQ',
    appId: '1:1039456219056:web:783196d691fd955a4d3075',
    messagingSenderId: '1039456219056',
    projectId: 'rubberquality-33cab',
    authDomain: 'rubberquality-33cab.firebaseapp.com',
    storageBucket: 'rubberquality-33cab.firebasestorage.app',
    measurementId: 'G-RZFE2DKGXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCExyleaIBGApwu-PoIoz_kTQ7Bzg8AGc',
    appId: '1:1039456219056:android:970395e26f0bceed4d3075',
    messagingSenderId: '1039456219056',
    projectId: 'rubberquality-33cab',
    storageBucket: 'rubberquality-33cab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvlDgF_jEj5u7CZrPvvC8DBO9tEQHgnoE',
    appId: '1:1039456219056:ios:2c1f2f7c9e6a33724d3075',
    messagingSenderId: '1039456219056',
    projectId: 'rubberquality-33cab',
    storageBucket: 'rubberquality-33cab.firebasestorage.app',
    iosClientId: '1039456219056-k5tc9ibjuedo60935m5so0h4hqh0s147.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvlDgF_jEj5u7CZrPvvC8DBO9tEQHgnoE',
    appId: '1:1039456219056:ios:2c1f2f7c9e6a33724d3075',
    messagingSenderId: '1039456219056',
    projectId: 'rubberquality-33cab',
    storageBucket: 'rubberquality-33cab.firebasestorage.app',
    iosClientId: '1039456219056-k5tc9ibjuedo60935m5so0h4hqh0s147.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaOIOHdDBhftD66uSiz41qmxC2aRMHepQ',
    appId: '1:1039456219056:web:eaf97acce023c2a14d3075',
    messagingSenderId: '1039456219056',
    projectId: 'rubberquality-33cab',
    authDomain: 'rubberquality-33cab.firebaseapp.com',
    storageBucket: 'rubberquality-33cab.firebasestorage.app',
    measurementId: 'G-2D2H555EQL',
  );
}
