// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaOIOHdDBhftD66uSiz41qmxC2aRMHepQ',
    appId: '1:1039456219056:web:783196d691fd955a4d3075',
    messagingSenderId: '1039456219056',
    projectId: 'rubberquality-33cab',
    authDomain: 'rubberquality-33cab.firebaseapp.com',
    databaseURL: 'https://rubberquality-33cab-default-rtdb.firebaseio.com',
    storageBucket: 'rubberquality-33cab.firebasestorage.app',
    measurementId: 'G-RZFE2DKGXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCExyleaIBGApwu-PoIoz_kTQ7Bzg8AGc',
    appId: '1:1039456219056:android:5b0f50bb901182c54d3075',
    messagingSenderId: '1039456219056',
    projectId: 'rubberquality-33cab',
    databaseURL: 'https://rubberquality-33cab-default-rtdb.firebaseio.com',
    storageBucket: 'rubberquality-33cab.firebasestorage.app',
  );
}